#%RAML 0.8

title: User Auth Module Routes
version: v1

/api/auth/forgot:
  post:

/api/auth/reset/{token}:
  get:
  post:


/api/auth/signup:
  post:

/api/auth/signin:
  post:

/api/auth/signout:
  get:

/api/auth/facebook:
  get:

/api/auth/facebook/callback:
  get:

/api/auth/twitter:
  get:

/api/auth/twitter/callback:
  get:

/api/auth/google:
  get:

/api/auth/google/callback:
  get:

/api/auth/linkedin:
  get:

/api/auth/linkedin/callback:
  get:

/api/auth/github:
  get:

/api/auth/github/callback:
  get:
