---
stages:
- name: Build
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: meanjs-build
    type: builder
    artifact_dir: ./
    build_type: gulp
    script: |-
      #!/bin/bash
      # Set Node version to 0.12
      export PATH=/opt/IBM/node-v0.12/bin:$PATH
      # Build MEANJS
      NODE_ENV=development npm install
      gulp build
- name: Deploy
  inputs:
  - type: job
    stage: Build
    job: meanjs-build
  jobs:
  - name: Deploy
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      cf push
      # view logs
      #cf logs "${CF_APP}" --recent
