#%RAML 0.8

title: Core Module Routes
version: v1
/server-error:
  get:
      responses:
        200:
          body:
            text/html:
  post:
/not-found:
  get:
      responses:
        200:
          body:
            text/html:

/i-dont-exist:
  get:

/*:
  get:
